version: "3.8"

services:
  api:
    container_name: boilerplate
    image: image:v1.0.0
    build:
      context: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - POSTGRES_HOST=
      - POSTGRES_PORT=
      - POSTGRES_USER=
      - POSTGRES_PWD=
      - POSTGRES_DB=
      - PORT=
      - AUTH_SECRET_KEY=
      - NODE_ENV=
      - CRON_RULE=
    network_mode: bridge
