version: "3.8"

services:
  api:
    container_name: crawl-data
    image: dockerdsm1.thegioiwhey.com/luannt201dev/crawl-data:v1.0.0
    build:
      context: .
    ports:
      - "5111:3000"
    restart: always
    environment:
      - POSTGRES_HOST=172.17.0.1
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=thegioiwhey@123
      - POSTGRES_DB=crawl_data
      - SAPOGO_ACCESS_TOKEN=6cbb64c0728f40f08d184e2b10842e81
      - TGW_URL=https://tgw.mysapogo.com/admin
      - X_SAPO_ACCOUNT_ID=865630
      - PORT=3000
      - MAX_RETRY_COUNT=10
      - AUTH_SECRET_KEY=thegioiwhey-super@secret
      - INCREMENT_RETRY_TIME=5
      - NODE_ENV=production
      - CRON_RULE='30 23 * * *'
      - CRAWL_GENERAL_API=http://172.17.0.1:50008
    network_mode: bridge
