version: "3.8"

services:
  api:
    container_name: crawl-data
    image: image:v1.0.0
    build:
      context: .
    ports:
      - "5111:3000"
    restart: always
    environment:
      - POSTGRES_HOST=
      - POSTGRES_PORT=
      - POSTGRES_USER=
      - POSTGRES_PWD=
      - POSTGRES_DB=
      - SAPOGO_ACCESS_TOKEN=
      - TGW_URL=
      - X_SAPO_ACCOUNT_ID=
      - PORT=
      - MAX_RETRY_COUNT=
      - AUTH_SECRET_KEY=
      - INCREMENT_RETRY_TIME=
      - NODE_ENV=
      - CRON_RULE=
      - CRAWL_GENERAL_API=
    network_mode: bridge
